### PR TITLE
Test with PHP 7.0

### PR DESCRIPTION
**Pull request by vinkla**
Run tests with PHP 7.0

### CODE REVIEW

**Comment by AydinHassan** [comment]
@vinkla how come this is closed?

**Comment by vinkla** [comment]
The tests failed. Maybe there is a workaround?

**Comment by AydinHassan** [comment]
It passed on 7, it seems the 5.5 build was unsuccessful, I think it just times out. Travis was being really slow and unresponsive for me yesterday.

**Comment by vinkla** [comment]
Yeah, maybe. Don't have time right now to push this again though. Maybe later.

**Comment by AydinHassan** [comment]
Sure. I can do it later if you don't have the time.

**Comment by vinkla** [comment]
:+1:

**Pull request closed without merging**
